### ISSUE TITLE
1.1.73 Update , translating dictionaries stuck at 1%

### ISSUE THREAD

**Issue by JayExplore** [nihilistzsche/LtnManager#200]
#### Describe the Bug

Translating dictionaries stuck at 1.1.73

#### To Reproduce

Updated game. dictionaries stopped at 1%

#### Save file & Username

https://we.tl/t-A0IQsP5NfR
XnagitoX

**Comment by raiguard** [comment]
This is due to a change in Factorio's locale system. I have determined the issue and filed a bug report with the Factorio devs. Once it is fixed, I will release an update to flib which will solve this problem.

It's not just affecting this mod, it's affecting any mod that uses flib's dictionary system.

https://forums.factorio.com/104297

**Comment by JayExplore** [comment]
Can confirm the problem still exists in 1.1.74

**Comment by raiguard** [comment]
Like I said, the fix requires updated to both Factorio and flib. I have pushed the flib 0.12 update, which fixes this.

**Comment by JayExplore** [comment]
Thanks. its fixed.
